"""CLI entry point for the simple ASR hotkey application."""

from __future__ import annotations

import argparse
import logging
from typing import Any

from simple_asr.app import AppConfig, SimpleASRApp


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simple on-device ASR with a press-to-talk hotkey.")
    parser.add_argument("--provider", default="canary", help="Name of the ASR provider to use (default: %(default)s).")
    parser.add_argument("--model-id", help="Override the model identifier for the provider.")
    parser.add_argument("--hotkey", default="f8", help="Keyboard key used to start/stop recording (default: %(default)s).")
    parser.add_argument(
        "--sample-rate",
        type=int,
        default=16000,
        help="Microphone sample rate to use when recording (default: %(default)s).",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=128,
        help="Maximum tokens generated by the Canary model (default: %(default)s).",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        help="Logging level (default: %(default)s).",
    )
    return parser.parse_args()


def configure_logging(level: str) -> None:
    numeric_level = getattr(logging, level.upper(), logging.INFO)
    logging.basicConfig(level=numeric_level, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")


def main() -> None:
    args = parse_args()
    configure_logging(args.log_level)

    provider_options: dict[str, Any] = {"max_new_tokens": args.max_new_tokens}

    config = AppConfig(
        provider_name=args.provider,
        hotkey=args.hotkey,
        model_id=args.model_id,
        sample_rate=args.sample_rate,
        provider_options=provider_options,
    )

    app = SimpleASRApp(config)
    app.run()


if __name__ == "__main__":
    main()
