"""CLI entry point for the simple ASR hotkey application."""

from __future__ import annotations

import argparse
import logging

from simple_asr.app import SimpleASRApp
from simple_asr.config import ConfigManager
from simple_asr.gui import start_gui
from simple_asr.vocabulary import DEFAULT_VOCAB_FILE, load_vocabulary, save_vocabulary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Simple on-device ASR with a press-to-talk hotkey."
    )
    parser.add_argument(
        "--provider",
        help="Name of the ASR provider to use (default from config or 'canary').",
    )
    parser.add_argument(
        "--model-id", help="Override the model identifier for the provider."
    )
    parser.add_argument(
        "--hotkey",
        help="Keyboard key used to start/stop recording (default from config or 'f8').",
    )
    parser.add_argument(
        "--sample-rate",
        type=int,
        help="Microphone sample rate to use when recording (default from config or 16000).",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        help="Maximum tokens generated by the Canary model (default from config or 128).",
    )
    parser.add_argument(
        "--vocab",
        nargs="*",
        default=None,
        help="Optional custom vocabulary phrases to bias transcription (repeatable).",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        help="Logging level (default: %(default)s).",
    )
    parser.add_argument(
        "--with-gui",
        action="store_true",
        help="Launch the web UI for live configuration management.",
    )
    parser.add_argument(
        "--gui-host",
        default="127.0.0.1",
        help="Host interface for the web UI (default: %(default)s).",
    )
    parser.add_argument(
        "--gui-port",
        type=int,
        default=8765,
        help="Port for the web UI (default: %(default)s).",
    )
    return parser.parse_args()


def configure_logging(level: str) -> None:
    numeric_level = getattr(logging, level.upper(), logging.INFO)
    logging.basicConfig(
        level=numeric_level,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )


def main() -> None:
    args = parse_args()
    configure_logging(args.log_level)

    config_manager = ConfigManager()
    config = config_manager.load()

    vocab_file = DEFAULT_VOCAB_FILE
    file_vocab = load_vocabulary(vocab_file)
    if file_vocab:
        config.provider_options["vocabulary"] = file_vocab

    if args.provider is not None:
        config.provider_name = args.provider
    if args.model_id is not None:
        config.model_id = args.model_id
    if args.hotkey is not None:
        config.hotkey = args.hotkey
    if args.sample_rate is not None:
        config.sample_rate = args.sample_rate
    if args.max_new_tokens is not None:
        config.provider_options["max_new_tokens"] = args.max_new_tokens
    if args.vocab is not None:
        config.provider_options["vocabulary"] = args.vocab
        save_vocabulary(args.vocab, vocab_file)
    else:
        save_vocabulary(config.provider_options.get("vocabulary", []), vocab_file)

    config_manager.save(config)

    app = SimpleASRApp(config)

    if args.with_gui:
        start_gui(
            app_instance=app,
            config_manager=config_manager,
            host=args.gui_host,
            port=args.gui_port,
            vocab_path=vocab_file,
        )

    app.run()


if __name__ == "__main__":
    main()
